config/routes.rb
Rails.application.routes.draw do
  #トップページをホームに
  root to: 'static_pages#home'
  #投稿用ルーティング
  resources :posts

  #管理者用ユーザールーティング
  namespace :admin do
    resources :users
  end

  #セッション用ルーティング
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :name, presence: true
    validates :name, length: { maximum: 50 }
    # validates :validate_name_not_include_comma
    belongs_to :user

    scope :recent, -> { order(created_at: :desc)}

    private
    #コンマを含めないようにするバリデーション
    def validate_name_not_include_comma
      errors.add(:name, 'にコンマを含めることはできません') if name&.include?(',')
      # &.を使っているのはnameがnilのときに例外が発生しないように(nilのときに検証が通るように)
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :posts
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin, only: [:edit, :update, :destroy]
  skip_before_action :login_required, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました！"
    else
      render :new, flash: { error: @user.errors.full_messages }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました！"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destoy
    redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を削除しました！"
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #セキュリティ対策構文
  protect_from_forgery with: :exception
  #すべてのビューでcurrent_userを使うためのヘルパーメソッド
  #ログイン情報の取得をかんたんにするため
  helper_method :current_user
  #ログインを要求するために処理を行う前に入れるフィルタ
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    #①User.findでも取得はできるが、findメソッドはnilのとき例外としてエラーが発生してしまう
    #そのため、例外が生じないようにこの場面ではfind_byを使用
    #②コントローラーではpublicなメソッドはアクションとしても利用できてしまうので、
    #プライベートメソッドとして使っている
    #③ifを中に入れているのはセッションが有効でない場合に取得を行わないため
  end

  def login_required
    redirect_to root_path unless current_user
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @user = @post.user
  end

  def create
    @post = current_user.posts.new(post_params)
    #ログイン中のユーザーが新規投稿する関連付けの書き方（オブジェクト指向っぽい書き方）
    #ログインしているユーザーのidがuser_idに入っている状態
    if @post.save
      #redirect_to @postでインスタンス変数にリダイレクトしているのは
      #posts/showのルーティングが@postで返されるため
      redirect_to @post, notice: "新規投稿が完了しました！"
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def update
    @post.update!(post_params)
    redirect_to posts_url, notice: "投稿を編集しました！"
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "投稿を削除しました！"
  end

  #ストロングパラメーターprivate
  private
  #nameとcontentは入力値を保持する必要があるのでそのメソッド
  def post_params
    params.require(:post).permit(:name, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #applicationcontrollerでbefore_actionが定義されているので
  #Sessionではそれをスキップするためのbefore_actionを入れる
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました'
      #メールアドレスに対するユーザーが見つからないとき、userはnilになってしまう
      #よって、ぼっち演算子を使用
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトが完了しました！'
    #reset_sessionはuser_idのセッション情報だけではなく、そのセッション内全ての情報を削除できる
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :login_required

  def home
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - @user.errors.full_messages.each do |message|
      li = message
/インデントに注意しないときちんと反映されない
= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      =f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード確認'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-success'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集
.nav.justify-content-end
  =link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧
= link_to '新規登録', new_admin_user_path, class: 'btn btn-success'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
    tbody
      - @users.each do |user|
        tr
          td= link_to user.name, [:admin, user]
          td= user.email
          td= user.admin? ? 'あり' : 'なし'
          td= user.created_at
          td= user.updated_at
          - if user.id == current_user.id
            td
              = link_to '編集', edit_admin_user_path(user), class: 'btn btn-success mr-3'
              = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}]を削除しますか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  - if current_user
    =link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザーの詳細
.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      td= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= Post.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= Post.human_attribute_name(:updated_at)
      td= @user.updated_at
- if @user.id == @current_user.id
  = link_to '編集', edit_admin_user_path, class: 'btn btn-success mr-3'
  = link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}]を削除しますか？" }, class: 'btn btn-danger'
/method: :deleteはデリートで返すため

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1"
    title
      | CycleSpotter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body.background
  .app-title.navbar.navbar-expand-md.navbar-light.bg-light
    .navbar-brand= link_to 'CycleSpotter', root_path, class: 'nav-link'

    u1.navbar-nav.m1-auto
      - if current_user
        li.nav-item= link_to '投稿一覧', posts_path, class: 'nav-link'
        li.nav-item= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
        li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
      /メソッドdeleteはブラウザがgetではなくdeleteを受け取るようにするための処理
      - else
        li.nav-item= link_to 'ログインはこちら', login_path, class: 'nav-link'
  .container
    / フラッシュメッセージが存在していればアラート属性でメッセージを表示
    -if flash.notice.present?
      .alert.alert-success= flash.notice
    = yield

app/views/posts/_form.html.slim
- if post.errors.present?#エラーが存在しているかどうか
  ul#error_explanation
    - @post.errors.full_messages.each do |message|
      li = message
/インデントに注意しないときちんと反映されない
= form_with model: @post, local: true do |f|
  .form-group
    = f.label :タイトル
    = f.text_field :name, class: 'form-control', id: 'post_name'
  .form-group
    = f.label :投稿内容
    = f.text_area :content, rows: 5, class: 'form-control', id: 'post_content'
  = f.submit nil, class: 'btn btn-success'

app/views/posts/destroy.html.slim
h1 Posts#destroy
p Find me in app/views/posts/destroy.html.slim

app/views/posts/edit.html.slim
h1 編集画面

.nav.justify-content-end
  = link_to '一覧', posts_path, class: 'nav-link'
  /renderはパーシャルの'_form'を呼び出すため
  /locals: { post: @post }は_formに
  /インスタンス変数@postを利用しなくてもpostで利用できるようにした
= render partial: 'form', locals: { post: @post }

app/views/posts/index.html.slim
h1 投稿一覧
= link_to '新規スポット登録', new_post_path, class: 'btn btn-success'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Post.human_attribute_name(:投稿者名)
      th= Post.human_attribute_name(:スポット一覧)
      th= Post.human_attribute_name(:created_at)
      th
    tbody
      - @posts.each do |post|
        tr
          td= link_to post.user.name, admin_users_url
          td= link_to post.name, post_path(post)
          td= post.created_at
          td
            / = link_to '編集', edit_post_path(@post), class: 'btn btn-success mr-3'
            = link_to '削除', post, method: :delete, data: { confirm: "投稿「#{post.name}]を削除しますか？" }, class: 'btn btn-danger'

app/views/posts/new.html.slim
h1 スポットの新規登録

.nav.justify-content-end
  = link_to '一覧', posts_path, class: 'nav-link'
/renderはパーシャルの'_form'を呼び出すため
/locals: { post: @post }は_formに
/インスタンス変数@postを利用しなくてもpostで利用できるようにした
= render partial: 'form', locals: { post: @post }

app/views/posts/show.html.slim
h1 スポット詳細
.nav.justify-content-end
  = link_to '一覧', posts_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= Post.human_attribute_name(:name)
      td= @post.name
    tr
      th= Post.human_attribute_name(:content)
      td= auto_link(simple_format(h(@post.content), {}, sanitize: false, wrapper_tag: "div"))
    tr
      th= Post.human_attribute_name(:created_at)
      td= @post.created_at
    tr
      th= Post.human_attribute_name(:updated_at)
      td= @post.updated_at
- if @post.user_id == @current_user.id
  = link_to '編集', edit_post_path, class: 'btn btn-success mr-3'
  = link_to '削除', @post, method: :delete, data: { confirm: "投稿「#{@post.name}]を削除しますか？" }, class: 'btn btn-danger'
/method: :deleteはデリートで返すため

app/views/static_pages/home.html.slim
.jumbotron
  .container
    - unless current_user
      h1 CycleSpotterの機能概要
      h3 ・サイクリングスポットの投稿機能
      h3 ・写真の投稿機能
      h3 ・GoogleMapとの連携機能
    - if current_user
      = link_to 'さあ、スポットを登録しよう！', new_post_path, class: 'btn btn-success'
    - unless current_user
      = link_to '新規ユーザー登録', new_admin_user_path, class: 'btn btn-success'
    h2 ↓詳しくは画面下へ↓
.row
  .container
    h2 使い方
    / img src="assets/login.jpg"
    p ①会員登録完了後、画面上のログインボタンをクリックしてログインしてください。
    / img src="assets/spot_create.jpg"
    p ②ログイン完了後、ホームページ中央の緑のボタンをクリックしてください。
    p ③投稿画面に遷移するので、タイトル、投稿内容、画像の投稿、スポットの登録をしてください。